name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build output not found!"
            exit 1
          fi
          echo "✅ Build output verified"

      - name: Test Action (Dry Run)
        uses: ./
        with:
          jira-base-url: "https://test.atlassian.net"
          jira-email: "test@example.com"
          jira-api-token: "fake-token"
          in-progress-transition-id: "1"
          under-review-transition-id: "2"
          done-transition-id: "3"

  check-dist:
    name: Check Build Output
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Compare built output
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Built output differs from committed dist/"
            echo "Please run 'npm run build' and commit the changes"
            echo ""
            echo "Diff:"
            git diff --ignore-space-at-eol dist/
            exit 1
          fi
          echo "✅ Built output matches committed dist/"
